[package]
name = "cvcap"
version = "0.1.2"
edition = "2021"
authors = [ "Crispin Bennett" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
ureq = {version = "2.4.0", features = ["json"]}
serde = {version = "1.0.137",features=["derive"]} 
serde_json = "1.0.81"
clap = {version = "3.1.18", features = ["derive"]}
directories = "4.0.1" 
toml = "0.5.9"
env_logger = "0.9.0" 
anyhow = "1.0.58" 
log = "0.4.17"
keyring = "1.2.0"
whoami = "1.2.1"
dialoguer = "0.10.1"
copypasta = "0.8.1"
atty = "0.2.14"
termcolor = "1.1.3"

[dev-dependencies]
mockito = "0.31.0"
assert_cmd = "2.0.4"
predicates = "2.0.3"
temp-dir = "0.1.11"
uuid = {version = "1.1.2", features = ["v4", "fast-rng"]}
