[package]
name = "checkvistcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.0", features=["full"]}
reqwest = {version = "0.11.10", features=["blocking"]} 
serde_json = "1.0.81"
url = "2.2.2"
serde = {version = "1.0.137", features=["std", "serde_derive"]}