use anyhow::Error;
use cvcap::app::cli;
use env_logger::Env;
use log::{error, info};

use cvapi::CheckvistError;
use cvcap::colour_output::{ColourOutput, StreamKind, Style};
use cvcap::{creds, Action, Cli, Error as AppError, RunType};

// Logging.
// Convention: reserve trace and debug levels for libraries (eg. checkvist api)
// Levels used in executable:
// - error: any non-recoverable error (eg. inability to parse config toml)
// - warn: recoverable errors
// - info: transient info for debugging

// Exit codes
// 0 - success
// 1 - any error generated by cvcap
// 2 - arg parsing errors

fn main() {
    let cli = Cli::parse();
    let subcommand = cli.subcommand;
    let allow_interaction = cli.interactivity_level != cli::InteractivityLevel::Silent;
    let context = match subcommand.new_context(allow_interaction) {
        Ok(context) => context,
        Err(e) => std::process::exit(handle_error(e, allow_interaction, "")),
    };

    let log_level = if cli.interactivity_level == cli::InteractivityLevel::Verbose {
        "DEBUG"
    } else {
        "OFF"
    };
    env_logger::Builder::from_env(Env::default().default_filter_or(log_level)).init();

    match subcommand.run(context.clone()) {
        Err(err) => {
            error!("Fatal error. Cause: {:?}", err.root_cause());
            std::process::exit(handle_error(
                err,
                allow_interaction,
                &context.keychain_service_name,
            ));
        }
        Ok(RunType::Completed(msg)) => {
            if allow_interaction {
                println!("{}", msg)
            }
        }
        Ok(RunType::Cancelled) => {
            if allow_interaction {
                println!("Cancelled")
            }
        }
    }
    std::process::exit(0);
}

fn handle_error(err: Error, allow_interaction: bool, keychain_service_name: &str) -> i32 {
    // CheckVistError
    // Hacky: downcast the concrete error types
    // requiring specific handling
    match err.root_cause().downcast_ref::<CheckvistError>() {
        Some(CheckvistError::InvalidListError) => eprint_error("Couldn't find or access the list you are trying to add to.\nAre you using an invalid bookmark?", allow_interaction),
        Some(CheckvistError::InvalidParentIdError) => eprint_error("Couldn't find the task you are trying to add a child task to.\nAre you using an valid bookmark?", allow_interaction),
        Some(CheckvistError::TokenRefreshFailedError) => { eprint_logged_out(allow_interaction);
            match creds::delete_api_token(keychain_service_name) {
                Err(err) => error!("Something went wrong deleting invalid api token: {}", err),
                _ => info!("Expired api token was deleted"),
            }
        }
        _possible_app_error => match err.downcast_ref::<AppError>() {
            Some(AppError::Reportable(msg)) => eprint_error(msg, allow_interaction),
            _all_other_errors => {
                eprint_unexpected_error(err, allow_interaction);
            }
        },
    }
    1
}

#[inline(always)]
fn eprint_error(message: &str, allow_interaction: bool) {
    if !allow_interaction {
        return;
    };

    let out = ColourOutput::new(StreamKind::Stderr);
    out.append("\nError: ", Style::Error)
        .append(message, Style::Normal)
        .println()
        .expect("problem styling error text");
}

#[inline(always)]
fn eprint_logged_out(allow_interaction: bool) {
    if !allow_interaction {
        return;
    }

    eprintln!(
        r#"
    You have been logged out of the Checkvist API.
    Please run cvcap again to log back in"#
    );
}

#[inline(always)]
fn eprint_unexpected_error(err: Error, allow_interaction: bool) {
    if !allow_interaction {
        return;
    }

    let err_msg: String = format!(
        r#"

    If you want to report this, fill out an issue at 
    {}.

    To gather more details that might help solve the issue, 
    run the same command again with the '-v' switch, and
    copy the output into the issue.
            "#,
        "https://github.com/crispinb/cvcap/issues"
    );

    let out = ColourOutput::new(StreamKind::Stderr);
    out.append(format!("\nError: {}", err), Style::Error)
        .append(err_msg, Style::Normal)
        .println()
        .expect("problem styling error text");
}
